version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - DATABASE_URL=postgresql://postgres:^admin123%@db:5432/spacious
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
